name: 'Swift Action'
description: 'Provides Swift support for GitHub Actions.'
inputs:
  run-task:
    description: 'Swift action to run'
    required: true
    default: 'build'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.run-task }}
