on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout Repository
    - uses: ./
      name: Run Swift Action
      with:
        swift-action: '--version'
